<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>DiskOptimizer.Models</RootNamespace>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <AnalysisLevel>latest</AnalysisLevel>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../Models/**/*.cs" Link="Models/%(RecursiveDir)%(Filename)%(Extension)" />
  </ItemGroup>
</Project>
